// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shopList.Entity;

#nullable disable

namespace shopList.Entity.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("shopList.Entity.Models.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("admin", (string)null);
                });

            modelBuilder.Entity("shopList.Entity.Models.Buyer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserlId")
                        .HasColumnType("uniqueidentifier");


                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Buyer", (string)null);
                });

            modelBuilder.Entity("shopList.Entity.Models.ProductList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");
                    b.HasIndex("ProductId");

                    b.ToTable("ProductList", (string)null);
                });

            modelBuilder.Entity("shopList.Entity.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("shopList.Entity.Models.Salesmen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Salesmen", (string)null);
                });

            modelBuilder.Entity("shopList.Entity.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SalesmenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductInStockId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SalesmenId");
                    b.HasIndex("DiscriptionId");
                    b.HasIndex("ProductInStockId");

                    b.ToTable("Product", (string)null);
                });
                
            modelBuilder.Entity("shopList.Entity.Models.ProductInStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Count")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("ProductInStock", (string)null);
                });

            modelBuilder.Entity("shopList.Entity.Models.Discription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Country")
                        .HasColumnType("uniqueidentifier");
                             
                    b.Property<string>("Material")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Weight")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Size")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("Discription", (string)null);
                });

            modelBuilder.Entity("shopList.Entity.Models.Salesmen", b =>
                {
                    b.HasOne("TVprogram.Entity.Models.User", "User")
                        .WithMany("Salesmen")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("shopList.Entity.Models.Buyer", b =>
                {
                    b.HasOne("shopList.Entity.Models.User", "User")
                        .WithMany("Buyer")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("shopList.Entity.Models.ProductList", b =>
                {
                    b.HasOne("shopList.Entity.Models.Buyer", "Buyer")
                        .WithMany("ProductList")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("shopList.Entity.Models.Product", "Product")
                        .WithMany("ProductList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("shopList.Entity.Models.Product", b =>
                {
                    b.HasOne("shopList.Entity.Models.Salesmen", "Salesmen")
                        .WithMany("Product")
                        .HasForeignKey("SalesmenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("shopList.Entity.Models.Description", "Description")
                        .WithMany("Product")
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("shopList.Entity.Models.ProgramInStock", "ProgramInStock")
                        .WithMany("Product")
                        .HasForeignKey("productInStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salesmen");

                    b.Navigation("Description");

                    b.Navigation("ProgramInStock");
                });

            modelBuilder.Entity("shopList.Entity.Models.Discription", b =>
                {
                    b.Navigation("Product");

                });

            modelBuilder.Entity("shopList.Entity.Models.ProductInStock", b =>
                {
                    b.Navigation("Product");

                });

            modelBuilder.Entity("shopList.Entity.Models.User", b =>
                {
                    b.Navigation("Buyer");
                    b.Navigation("Salesmen");
                });
#pragma warning restore 612, 618
        }
    }
}
